[pytest]
pythonpath = .
addopts = -s --tb=short --showlocals -p no:faulthandler
faulthandler_timeout = 0
log_cli = true
log_cli_level = WARNING
filterwarnings =
    ignore::UserWarning:pywinauto.*
    ignore::DeprecationWarning:pywinauto.*
    ignore::pytest.PytestUnknownMarkWarning
markers =
    UD_tags: User defined tags tests
    dependency: dependency tests
    other: other tests
    modbus_tcp_client: modbus tcp client tests
    menu_bar: menu bar tests
    io_config: io config tests
    expansion: expansion tests
    other1: other1 tests
    other2: other2 tests
    other6: other6 tests
